CHANGELOG.md
lib/slimmer/version.rb

* Remove AlphaLabelInserter, BetaNoticeInserter, BetaLabelInserter. These are
now better handled by govuk_components
* Remove LogoClassInserter. BusinessLink and DirectGov branding is being
removed so we don't need to insert their logos
* Loosen Nokogiri dependency. Rails 4.2 needs Nokogiri 1.6.0 and above.

Bump version to 7.0.0

---

lib/slimmer/processors/google_analytics_configurator.rb
test/processors/google_analytics_test.rb

As part of moving analytics from classic to universal, we’ve audited the custom variables being set and whether they are still being used. Ash identified this variable as being unused and marked it for deletion.
Part of https://www.pivotaltracker.com/story/show/87740262

Remove business proposition custom variable

---

lib/slimmer/processors/google_analytics_configurator.rb
test/fixtures/wrapper.html.erb
test/processors/google_analytics_test.rb

These variables were added to test guide success tracking in:
https://github.com/alphagov/slimmer/pull/5
That success tracking was removed in:
https://github.com/alphagov/static/pull/522
They are no longer used and the “Analytics” namespace is being removed.

Remove `GOVUK.Analytics` variables

---

lib/slimmer/headers.rb

It isn't being obviously used anywhere and no tests fail.

Remove the 'Proposition' header

---

lib/slimmer.rb
lib/slimmer/headers.rb
lib/slimmer/processors/search_remover.rb
lib/slimmer/skin.rb
test/processors/search_remover_test.rb

For manuals we need to remove the search box in the page header as we're going to be adding one that provides custom searching within the manual.
This commit adds a new `header` that you can call from your app that will remove the search box from the top of the page.
You can call it by adding the following code to your applications ApplicationController in a before filter:
`set_slimmer_headers(remove_search: true)`
Pivotal:https://www.pivotaltracker.com/n/projects/1261204/stories/88435634
This PR defines the header and adds the processor for the header and a test for the processor.
Further work
- After this header is merged we should start using it in frontend too which currently uses CSS to `display:none` the top search box on /search and the homepage (I'll open a PR...)

Add a header to remove search bar

---

lib/slimmer/processors/metadata_inserter.rb
lib/slimmer/railtie.rb
lib/slimmer/skin.rb

I am interested in thoughts on this being a thing that should exist as much as the technical implementation of this change. Do you think this is a good idea?
New pull request because I force pushed to the [last one](https://github.com/alphagov/slimmer/pull/125) while it was closed so can't reopen it :cry: 
-----
It would be really useful to be able to segment analytics by rendering
application. It would let us have things like JavaScript errors per
application and page timings per application.
This change takes the class name of the currently running application
and adds it as a meta tag which can then be read by JavaScript.

Output rendering application in meta tag

---

lib/slimmer/railtie.rb

Rather than using the applications class name use the GOVU_APP_NAME
environment variable if it is around. This will then better match the
names we use within the infrastructure, and also match the vhost
name.

Use GOVUK_APP_NAME if it is set

---

CHANGELOG.md
lib/slimmer/version.rb

Update rendering app meta tag to use GOVUK_APP_NAME env variable if
available

Bump to 8.2.1

---

lib/slimmer/processors/tag_mover.rb
test/processors/tag_mover_test.rb

Previously, slimmer skipped meta tags with no name set, which dropped
OpenGraph and Twitter meta tags. This now separately copies these
over.
Also adding tests for meta tag with property and test for duplicate property meta tags
NB was previously discussed in #132, but due to rebase / squash and exisiting commits to forked repo, had to abandon that PR and open this one...

Copying meta tags with property

---

CHANGELOG.md
lib/slimmer/version.rb

**Versioning**:
This could be minor or patch, depending how you look at it, so made it minor to be on the safe side.
**Changes** ([diff](https://github.com/alphagov/slimmer/compare/v8.3.0...2e87a0a367f8e671fe3ec33820d528b1b2a1bfcf)):
* Add support for moving `meta` tags that use `property` attribute
Previously only meta tags using the `name` attribute were moved into the
`head` of the page. This allows OpenGraph-style meta tags to be included
by an application using Slimmer.
**Contributors**: 
- @gilesdring

Version 8.4.0

---

jenkins.sh
slimmer.gemspec

It's configured to only report on the diff of changes, not the whole repo.
I've run it against the whole repo and there a reasonable amount of violations,
and bulk fixing them is usually contentious, so i'm ignoring that for now.
With this linting in place at least nothing new will violate the style guide
and hopefully this will mean computers can give the feedback on style issues,
rather humans, which computers are better at and avoids humans having to give
nitpick-y feedback.
CC @boffbowsh who wrote the linting gem, and @edds, @alext and @jamiecobbett as people who've worked on slimmer.
Thoughts?

Run GOV.UK ruby linter as part of CI builds

---

lib/slimmer/component_resolver.rb
slimmer.gemspec
test/component_resolver_test.rb

CVE-2016-0752 was announced, the fix for which changed how Rails calls
template resolvers. It added an optional argument (defaulting to false)
which controls whether the template resolver should find templates
outside `Rails.root`. In Slimmer’s case, we take any requested
templates with a prefix of `govuk_component`and resolve them with the
static service over HTTP. The local file system is never touched.
Therefore, it’s safe to simply add the new argument here but ignore it
and carry on as normal.
/cc @dsingleton

Add optional arg to template resolver call

---

lib/slimmer/component_resolver.rb
test/component_resolver_test.rb

For components to be able to call other components (composeable components) they need to use a component path that includes `.raw` (this is not a standard Rails format, but a convention
we use).
Consider the following component:
```erb
<div class="govuk-govspeak-html-publication">
<%= partial: 'govuk_component/govspeak', locals: govspeak_locals %>
</div>
```
In this example, the application can make a request for the `govspeak-html-publication` component (`govuk_component/govspeak-html-publication.raw.html.erb`), and then a subsequent request for `govspeak`, both will work. Slimmer converts the component name into a filename.
When testing in static we don't use slimmer, so the test attempts to load `govuk_component/govspeak.html.erb` rather than `govspeak.raw.html.erb` version. That files …

Accept full and partial component paths in resolver

---

CHANGELOG.md
lib/slimmer/version.rb

Allow applications to request components using full or partial component paths, eg "name", "name.raw" and "name.raw.html.erb". This allows components to be nested within other components. https://github.com/alphagov/slimmer/pull/140

Version 9.1.0

---

lib/slimmer/skin.rb
test/skin_test.rb

Raise a custom `CouldNotRetrieveTemplate` exception when a connection to the assets server can't be made because of some SSL problem.
I've seen this problem a few times in development and at least once in Smart Answers production (see [errbit error][1]).
In case it's useful, I used cURL to make the request when I experienced this problem in development:
$ curl -v \
https://assets-origin.integration.publishing.service.gov.uk/templates/wrapper.html.erb
*   Trying 31.210.245.98...
* Connected to
* assets-origin.integration.publishing.service.gov.uk
* (31.210.245.98) port 443 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
Trying to connect to assets server using cURL gives this information:
[1]: …

Rescue SSL errors in Skin#load_template

---

CHANGELOG.md
lib/slimmer/version.rb

I've incremented the minor version as I believe the change in PR #143
(the only change made since 9.1.0) counts as "add(ing) functionality in
a backwards-compatible manner"[1].
[1]: http://semver.org/

Bump version to 9.2.0

---

lib/slimmer/shared_templates.rb

The `before_filter` method is deprecated and will be removed in Rails 5.1. Fixing now so that we don't pollute our logs with depreciation warnings.

Replace deprecated `before_filter` calls

---

lib/slimmer.rb
lib/slimmer/i18n_backend.rb
lib/slimmer/railtie.rb
lib/slimmer/shared_templates.rb
slimmer.gemspec

Continues the work started in https://github.com/alphagov/static/pull/505
Let's slimmer chain it's own i18n backend to the frontend app that consumes it.

Autoload i18n backend

---

LICENSE
slimmer.gemspec

Closes https://github.com/alphagov/slimmer/issues/48
We should probably audit all the repos and make sure they have the correct licenses too..

Add MIT license to repo

---

lib/slimmer/test_helpers/shared_templates.rb

Allows frontend apps to stub component locales for example
```ruby
class ActiveSupport::TestCase
include Slimmer::TestHelpers::SharedTemplates
def setup
stub_shared_component_locales
end
end
```

Add shared test helper for frontend app to use

---

lib/slimmer/shared_templates.rb

Checks if the Slimmer i18n backend has already been chained onto the
backend before adding it. This fixes a recursion issue where over time
the I18n backend would become a chained backend of chained backends
many times over.
/cc @gpeng @nickcolley

Don't chain i18n backend multiple times

---

README.md
lib/slimmer/rspec.rb
lib/slimmer/test_helpers/shared_templates.rb

These changes make the `stub_shared_component_locales` test helper more robust so that it correctly stubs requests originating from a host application.
Currently Slimmer will attempt to make external HTTP requests to fetch locale information when rendering its templates.
```
Failure/Error: <%= render partial: 'govuk_component/beta_label' %>
WebMock::NetConnectNotAllowedError:
Real HTTP connections are disabled. Unregistered request: GET http://static.dev.gov.uk/templates/locales with headers {'Accept'=>'*/*; q=0.5, application/xml', 'Accept-Encoding'=>'gzip, deflate', 'User-Agent'=>'Ruby'}
You can stub this request with the following snippet:
stub_request(:get, "http://static.dev.gov.uk/templates/locales").
with(:headers => {'Accept'=>'*/*; q=0.5, application/xml', …
```

Fix component locale stubs

---

CHANGELOG.md
lib/slimmer/version.rb

Adds an RSpec helper that makes it easy for host applications to configure Slimmer correctly under test.
Fixes `stub_shared_component_locales` helper to correctly stub HTTP requests to fetch locale information when rendering its templates.

Bump version to 9.4.0

---

CHANGELOG.md
lib/slimmer/version.rb

Adds a Cucumber helper that makes it easy for host applications to configure Slimmer correctly under test.

Bump version to 9.5.0

---

Rakefile
jenkins.sh
lib/tasks/lint.rake

Add a rake task to run the linter in the same way that CI runs it, so you can now just `bundle exec rake lint`.
Also change the default rake task to run tests and then lint, which follows the same pattern used in other repos.

Make it easier to run the linter locally

---

lib/slimmer.rb
lib/slimmer/processors/inside_header_inserter.rb
lib/slimmer/skin.rb
test/processors/inside_header_inserter_test.rb

This processor allows an application to inject a block of HTML after the logo by including a `.inside-header` element in their application’s output.
This is effectively like adding content to the inside_header yield block in govuk_template.
The service manual is using this to insert a title into the header.

Add an ‘inside header’ inserter

---

CHANGELOG.md
lib/slimmer/processors/metadata_inserter.rb
test/artefact_test.rb
test/headers_test.rb
test/processors/metadata_inserter_test.rb

This commit removes the need IDs meta tag. The performance analysts confirmed at a meeting on 12/10/2016 that this tag is no longer required.
https://trello.com/c/WUiqJuh6/188-remove-govuk-need-ids-meta-tag

Remove need IDs meta tag

---

CHANGELOG.md
jenkins.sh

Because:
- We have only one app running 3.X (design-principles, which will be removed in the future)
- There are no apps using slimmer that run Rails 4.1
- No apps that run 1.9.3 or 2.1
Source:
https://docs.google.com/spreadsheets/d/1FJmr39c9eXgpA-qHUU6GAbbJrnenc0P7JcyY2NB9PgU/edit#gid=1480786499

Drop testing for Rails 3.2, 4.1, Ruby 1.9.3 and 2.1

---

gemfiles/Gemfile.rails-3.2.x
gemfiles/Gemfile.rails-4.1.x

Support for these versions was dropped in https://github.com/alphagov/slimmer/pull/174.

Remove old testing Gemfiles

---

CHANGELOG.md
README.md
lib/slimmer.rb
lib/slimmer/cucumber.rb
lib/slimmer/govuk_components.rb
lib/slimmer/rspec.rb
lib/slimmer/test_helpers/govuk_components.rb
test/test_helpers/govuk_components_test.rb

We're updating slimmer across a lot of apps with breaking changes, so I thought to rename a few things for consistency while we're upgrading things.
We're already calling this functionality "GOV.UK components" in most places. For consistency this renames the modules that we include into the controller and tests.
```ruby
class ApplicationController < ActionController::Base
include Slimmer::SharedTemplates
end
```
```ruby
class ApplicationController < ActionController::Base
include Slimmer::GovukComponents
end
```
Closes https://github.com/alphagov/slimmer/issues/169.
After merge:

Rename SharedTemplates to GovukComponents

---

CHANGELOG.md
lib/slimmer/version.rb

This anniversary edition of slimmer:
* Removes the need_id meta tag, which is no longer used.
* Removes the functionality for breadcrumbs, related links and artefact-powered metatags.
* Drop support for old Rails & Ruby versions. This gem now supports Rails 4.2 and 5.X on Ruby 2.1 and 2.2.
* Renames `Slimmer::SharedTemplates` to `Slimmer::GovukComponents`

Release Slimmer 10.0.0

---

slimmer.gemspec

When the test/spec directory is mentioned on the gemspec it actually
bundles the gem with those files.
There's also no reason to send the test files to production.
Replaces: https://github.com/alphagov/slimmer/pull/178

Remove test files from the built gem

---

CHANGELOG.md
lib/slimmer.rb
lib/slimmer/component_resolver.rb
lib/slimmer/govuk_request_id.rb
lib/slimmer/http_client.rb
lib/slimmer/i18n_backend.rb
lib/slimmer/skin.rb
test/http_client_test.rb
test/skin_test.rb

Related to https://github.com/alphagov/slimmer/pull/183, this adds a `User-Agent` header to all requests to `static`, just like gds-api-adapters does. This will make it easier for us to see where requests come from.
https://trello.com/c/D9HmkJwI

Add a user agent header for all requests

---

CHANGELOG.md
lib/slimmer/version.rb
test/http_client_test.rb

Improves caching and adds user agent to outgoing requests. Be sure to remove the `slimmer.use_cache` config from your initialiser.

Release 10.1.0

---

lib/slimmer/skin.rb
test/processors/search_parameter_inserter_test.rb

This small change is the result of a long and complicated hunt into a
mysterious bug that was occurring approximately 4000 times a day on
Whitehall.
It is possible that GOV.UK may receive requests that have Unicode
characters in them. These are invalid as URIs as Unicode character must
be percent escaped. However unlike github - which will reject Unicode
characters with a 400 Bad Request - we will accept them.
This leaves is somewhat undefined waters where ruby servers may differ
in how they handle the request. Unicorn converts the request into an
ASCII encoded string. Normally this isn't a problem unless this string
contains a character outside of the range compatible with Unicode.
When this does occur though it raises an error when this string is
concatenated with the UTF-8 template. …

Force request url to be UTF-8 encoding

---

CHANGELOG.md
lib/slimmer/version.rb

Bugfix for request URI's encoded as ASCII

Bump to 10.1.2

---

CHANGELOG.md
lib/slimmer/component_resolver.rb
lib/slimmer/govuk_components.rb

Most of our frontend apps leak memory, which causes regular Icinga alerts for 2nd line. We currently mitigate this by restarting the apps manually.
This dashboard shows the problem: https://grafana.publishing.service.gov.uk/dashboard/db/memory-dashboard
The primary cause of this seems to be the `GovukComponent` class. This currently instantiates a `ComponentResolver` class per request, which in turn instantiates lots of ActionView related objects.
By caching the resolver for 15 minutes, we save a lot of memory.
To test I've used the [derailed_benchmarks gem][derailed]. I've tested this with the following command on `government-frontend`:
[derailed]: https://github.com/schneems/derailed_benchmarks
```
GOVUK_APP_DOMAIN=www.gov.uk GOVUK_ASSET_ROOT=https://www.gov.uk …
```

Fix memory leak in components

---

CHANGELOG.md
lib/slimmer/skin.rb
lib/slimmer/version.rb

Airbrake has removed the notify_or_ignore, in favour of just notify
i fixed this by just making it go through notify, which exists in
airbake 4 and 5
https://github.com/airbrake/airbrake/blob/master/docs/Migration_guide_from_v4_to_v5.md#notify-or-ignore

Change airbrake call to be compatible with airbrake v5

---

slimmer.gemspec

This commit upgrades the `nokogiri` dependency to `~> 1.7` due to a number of security vulnerabilities with `~> 1.6`, to allow apps using `nokogiri` to upgrade their versions.

Upgrade nokogiri dependency

---

lib/slimmer/skin.rb

When the body inserter fails, the page errors but the resulting error gets cached. This means the cached error pages get seen by users.  Raise errors to avoid caching an incorrect page.
Now we are no longer catching errors we do not need to specifically call Airbrake. We are also moving away from Airbrake.
Follow on from #202 and https://github.com/alphagov/government-frontend/pull/446
cc @tijmenb

Do not catch errors from Slimmer processors

---

lib/slimmer/skin.rb

When the body inserter fails, the page errors but the resulting error
gets cached. This means the cached error pages gets seen by users.
Raise error to avoid caching an incorrect page.
(We're pointing government-frontend at this branch here: https://github.com/alphagov/government-frontend/pull/445)

Raise error so pages are not cached

---

CHANGELOG.md
lib/slimmer/version.rb

* Stop catching errors from Slimmer processors (#203)
* Removes all references to Airbrake

Version 11.0.1

---

lib/slimmer/test_templates/header_footer_only.html
lib/slimmer/test_templates/proposition_menu.html
lib/slimmer/test_templates/wrapper.html

When using slimmer in test mode, instead of getting templates from Static it returns these test templates. They were missing some class tags as required by the NavigationMover class, which in turn made Whitehall tests fail (in a not very obvious way).
Alternative for https://github.com/alphagov/slimmer/pull/205
See Whitehall failures here: https://github.com/alphagov/whitehall/pull/3427

Add missing class tags to test templates

---

lib/slimmer/template.rb

[Trello card](https://trello.com/c/6BqK4u39/740-5-move-smart-answers-from-errbit-to-sentry)
Following the upgrade of govuk apps to rails 5, certain gems like this may not have been altered to match rails 5 apps. Also at the moment smart answer requires an update beyond 5.0.2 and this isn't possible becuase newer version of rails only support after_action.
This PR makes this switch under the assumption that all gov.uk apps are
now rails 5 compliant.

Replace after filter with after action

---

lib/slimmer.rb
lib/slimmer/component_resolver.rb
lib/slimmer/local_component_resolver.rb
lib/slimmer/local_govuk_components.rb
lib/slimmer/network_component_resolver.rb
test/component_resolver_test.rb
test/local_component_resolver_test.rb
test/network_component_resolver_test.rb
test/test_helper.rb

We need the option to use local components when using Slimmer in the static component guide (which lives in Static). This avoids network requests, excessive network stubbing and i18n chain hacks.
Because static components have a `.raw.html.erb` filename, we can’t use the default Rails component resolver. eg `govuk_component/title` can’t find the `_title` partial – we need to load `title.raw.html.erb`.
* Split ComponentResolver into LocalComponentResolver and NetworkComponentResolver
* Create new module for LocalGovukComponents which govuk_publishing_components can use when included on static
* LocalGovukComponents don’t need a test version
Alternative to: https://github.com/alphagov/static/pull/1144
The `LocalGovukComponents` will be loaded in the govuk_publishing_components gem when used …

Create local and network component resolvers

---

CHANGELOG.md
lib/slimmer/version.rb

* Allow components in static to be loaded locally rather than over the network (#208)
* Replace deprecated `after_filter` in slimmer_template (#209)

Version 11.1.0

---

lib/slimmer/processors/inside_header_inserter.rb
test/processors/inside_header_inserter_test.rb

Some applications (like Service Manual Frontend) opt into using Slimmer for their javascript tests (so that they get e.g. jQuery) but in a test context the header logo is stubbed out, so this breaks.
This was previously masked by Slimmer swallowing exceptions raised within the processors, but this was removed in #203.

Make 'inside header inserter' more resilient

---

CHANGELOG.md
lib/slimmer/processors/tag_mover.rb
test/processors/tag_mover_test.rb

When combining the template and application HTML, the `TagMover` will take the meta and script tags from the application HTML and move them to the bottom of the `<head>` tag.
`TagMover` moves them to the bottom, so that the CSS of the application can override the CSS of the template (there's even a test in this gem to make sure it does it like this).
However, the desired behaviour for meta tags is the reverse. In particular, we want the `og:image` from the application to be higher than the `og:image` from the template. This is because services like Slack will choose the first `og:image` tag and not the more appropriate custom one.
I tried to do this in https://github.com/alphagov/govuk_template/pull/349, but I forgot that life isn't easy and Slimmer exists.
Will enable …

Make sure we insert meta tags above template metatags

---

CHANGELOG.md
lib/slimmer.rb

We experienced an [incident yesterday][1] that might have been caught on staging if it wasn't for the delay between deploying to staging and the caches expiring. By moving to a minute long cache we increase the likelihood of noticing issues quickly after deploy.
The requests made are very fast anyway, so this is not likely to impact load speed very much.
[1]: https://docs.google.com/document/d/1Hyg48BZVi0gVFkYO2FMDv7F797X3pOi-wbc7pxzGTgE/edit#

Drop cache TTL to 60 seconds

---

CHANGELOG.md
lib/slimmer/test_templates/header_footer_only.html
lib/slimmer/test_templates/wrapper.html
test/test_template_dependency_on_static_test.rb

Dynamically adds `js-enabled` to the `body` tag of the test templates if the template is rendered by an engine that supports JavaScript. This allows us to test JavaScript behavior that is enabled by feature detection.
This mirrors the main GOV.UK template behavior in https://github.com/alphagov/govuk_template/blob/f2c10fae7ec7e371fd11c409cd71a399e3342e7f/source/views/layouts/govuk_template.html.erb#L40
Part of https://trello.com/c/VENEFcz5

Add `js-enabled` to test template body tag

---

slimmer.gemspec

This will allow us to use Ruby 2.6

Upgrade Webmock 3.4.2 => 3.5.0

---

slimmer.gemspec

This should fix trouble with Rails cops on CI (https://ci.integration.publishing.service.gov.uk/job/slimmer/job/olleolleolle-patch-1/2/console).

Bump govuk-lint

---

slimmer.gemspec

The RubyGems property rubyforge_project is removed without a replacement.

Gemspec: Drop EOL'd property rubyforge_project

---

CHANGELOG.md
lib/slimmer/version.rb

Bump the version and reflect the new version in the CHANGELOG so we can prompt the release of the gem.

Bump version to 13.2.0

---

CHANGELOG.md
lib/slimmer/railtie.rb
slimmer.gemspec
test/railtie_test.rb
test/test_apps/test_apps.rb
test/test_helper.rb

The method parent_name in Railtie was allowed to be called without an
argument. This commit adds the argument `app` and adds a test to ensure
the argument is not removed in future.
Trello card: https://trello.com/c/Ik7ulDXQ/1768-3-upgrade-frontend-to-rails-6
Co-Authored-By: Rebecca Pearce <rebecca.pearce@digital.cabinet-office.gov.uk>
Co-Authored-By: Alan Gabbianelli <alan.gabbianelli@digital.cabinet-office.gov.uk>

Fix bug where parent_name was called without app

---

lib/slimmer/app.rb
lib/slimmer/headers.rb
test/test_helper.rb
test/typical_usage_test.rb

Currently for all non-200 pages, Slimmer will replace the response body with templates from Static. This certain apps like email-alert-frontend need to present custom error page (e.g. 422). This allows an app to tell Slimmer not to override the error page with the one in Static.
The host app just needs to set the header `X-Slimmer-Ignore-Error: true`

Add header flag to allow custom error responses

---

CHANGELOG.md
lib/slimmer/app.rb
lib/slimmer/headers.rb
lib/slimmer/version.rb
test/railtie_test.rb
test/test_helper.rb
test/typical_usage_test.rb

https://trello.com/c/Uzpw1bDA/243-document-how-error-pages-work-on-govuk
Depends on: https://github.com/alphagov/email-alert-frontend/pull/774
This reverts commit 4a5172abbbeaa38b1985d46e755b78e70494253e.
Previously we added this header to support custom error page for a
specific error code, which wasn't handled by our infrastructure.
Since then, we've upgraded our infrastructure to provide a suitable
fallback that makes this change obsolete.
Although we may still need our apps to show more contextual error
responses, the general way we handle errors in our infrastructure
means all of these will need to be returned as 200 responses, to
avoid getting override downstream.

Revert "Add header flag to prevent overriding error responses"

---

CHANGELOG.md
lib/slimmer/processors/tag_mover.rb
test/processors/tag_mover_test.rb

This PR adds the `<base>` tag into the `<head>`. This change supports an upcoming change to Whitehall which specifies the `<base>` tag for the CSV preview endpoint to fix a long-standing issue with broken links in the footer pointing to the wrong website root.

Add base tag into the head

---

CHANGELOG.md
lib/slimmer/processors/search_remover.rb
test/processors/search_remover_test.rb

The code in `search_remover.rb` assumes that the search toggle button is a
link.
This is an issue as work is being done to change the markup of this
button for accessibility purposes.
Change the search toggle button selector to a class selector instead to
ensure that functionality is preserved when we change the anchor tag to
a button tag.
https://trello.com/c/WLq4rKrW

Amend toggle button selector

---

CHANGELOG.md
lib/slimmer.rb
lib/slimmer/headers.rb
lib/slimmer/processors/accounts_shower.rb
lib/slimmer/skin.rb
test/processors/accounts_shower_test.rb

The new show_accounts header has three states:
- "signed-in": remove the signed-out header
- "signed-out": remove the signed-in header
- anything else: remove both headers
I went for "Shower" over "Remover" because this has the opposite
behaviour to the SearchRemover: it removes the thing by default,
because we're only showing this header on a few pages.
---
[Trello card](https://trello.com/c/vdZrgBRy/363-make-changes-to-transition-for-trial-launch)

Add an "AccountsShower" processor to show / hide accounts headers

---

CHANGELOG.md
lib/slimmer.rb
lib/slimmer/skin.rb
lib/slimmer/version.rb
test/skin_test.rb

https://trello.com/c/qqGgd6mA/598-dev-pain-slimmer-causes-500-errors-for-transient-communication-errors-with-static
This separates certain kinds of unactionable exception
into a new, custom error, so that we can ignore them in
Sentry, much like we do for GDS API Adapters.
Before ignoring the errors, I also looked at whether we
could stop them from occurring in the first place, but
decided against making any changes:
- The local caching is deliberately short-lived, to avoid
false negative checks during deployment [1].
- The default timeouts are all 60 seconds [2], which is way
above what we have for GDS API Adapters.
Please see the commits for more details.
[1]: https://github.com/alphagov/slimmer/commit/b5f5b883500a3407eca10ec15b9068e075bf67fd
[2]: …

Prepare to ignore intermittent errors

---

.gitignore
.yardopts
docs/what-slimmer-does.md

At time of writing, this documentation (written in September 2012)
exists in the Slimmer Wiki on GitHub. We don't typically use wikis
in our repos, not least because we're beginning to import
documentation into https://docs.publishing.service.gov.uk/.
It contains useful context and should be more readily findable.
Our Rails conventions are that we store documentation in a folder
called `docs/` (https://github.com/alphagov/govuk-developer-docs/pull/2571),
and we plan on auto-ingesting docs folders into the Dev Docs in
the foreseeable future. It makes sense to have this useful doc
copied here in advance of that, and we can then delete the Wiki.

Copy 'What Slimmer Does' documentation

---

CHANGELOG.md
lib/slimmer/processors/tag_mover.rb
lib/slimmer/version.rb
test/processors/tag_mover_test.rb

Currently all script tags are moved to the bottom of the `body`.
It is  preferable, for `async` and `defer` script tags to be placed in the `head`, 
as their fetching and execution will not interfere with the parsing of the document.
Placing near the top of the head means their fetching can begin as soon as possible,
without waiting for other blocking tags such as CSS.
Scripts without `async` or `defer` attributes will continue to be placed at the bottom of the `body`.
[trello](https://trello.com/c/qUyucxL4/2296-5-support-async-and-defer-in-slimmer)

Ensure async and defer scripts are hoisted to the top of the head

---

lib/slimmer/processors/accounts_shower.rb
test/processors/accounts_shower_test.rb

During development the markup for the account nav (appears on the transition page, and transition checker) was copied over from the layout header component instead of using the component itself. This was probably due to time constraints.
The component audits are complaining that we are including the assets for `layout_header` in static, when we are not using the component.
To fix this problem, we are removing the hard coded account navigation from static, and using the layout header component in its place:  https://github.com/alphagov/static/pull/2408
That is technically duplicating the header – these changes are here to conditionally swap the `#global-header` for the `layout_header` only when the account is enabled and the account nav should be present.
https://trello.com/c/9Kjy1hjb

Add support for layout header component in static

---

lib/slimmer/processors/accounts_shower.rb
lib/slimmer/processors/search_remover.rb
test/fixtures/gem_layout.html.erb
test/processors/accounts_shower_test.rb
test/processors/search_remover_test.rb
test/test_helper.rb

Adds compatibility with the [public layout component][1] - allows search and the accounts links to be shown and hidden without removing other parts of the template.
Currently, the public layout component can't be used as a template. This is because Slimmer doesn't know which selectors to look for when removing aspects of the markup from the public layout component - search and navigation for example - which will be supplied by a new template in Static.
[1]: https://components.publishing.service.gov.uk/component-guide/layout_for_public

Add compatibility for the public layout component

---

lib/slimmer/processors/accounts_shower.rb
lib/slimmer/processors/body_inserter.rb
lib/slimmer/skin.rb
test/processors/accounts_shower_test.rb
test/processors/body_inserter_test.rb

When using the `gem_layout` template in statice, fixes layout issue in the header and allows CSS classes on both `#wrapper` elements to be merged.
These are `gem_layout` template specific changes, so won't affect pages using the `core_layout` template to preserve backwards compatibility.
When the navigation links were removed in the gem layout it would leave the wrapping element. The wrapping element had padding set on it which would cause the layout to shift even if there were no child elements. This change removes the wrapping element if there are no navigation links.
The gem layout template has classes that are needed on the `#wrapper` element - these classes are lost when the `body_inserter` moves the element from the source into the template. This change merges the classes on both …

Update `gem_layout` template support

---

CHANGELOG.md
lib/slimmer.rb
lib/slimmer/processors/feedback_url_swapper.rb
lib/slimmer/skin.rb
test/processors/feedback_url_swapper_test.rb

Adds a processor that searches for the two hidden input elements that allow the feedback component to report the URL, and updates the value of the inputs to the current page URL.
The feedback component has two hidden fields that allow it to tie a piece of feedback to a particular page. When the feedback component was rendered by the frontend application it could correctly populate this field - but when the feedback component was moved to the template rendered by Static it incorrectly eported the current URL as being the template URL.
Since Static doesn't have access to the URL, it needs to be swapped in using Slimmer in the frontend application - this searches for the two hidden input fields and corrects the value to the current page URL.
Fixing this in Slimmer rather than in Static means …

Add feedback URL swapper

---

lib/slimmer/processors/feedback_url_swapper.rb
test/processors/feedback_url_swapper_test.rb

Use the `&.` safe navigation operator in the feedback URL swapper.
Using `&.` is equivalent to `thing ? thing.some_method : thing` - so won't throw an error as `set_attribute` is not used.
This was causing lots of tests to fail because the HTML stubs for the tests didn't have the selector being searched for in them. This threw an error because `set_attribute` can't be used on nil.

Use safe navigation operator in feedback url swapper

---

CHANGELOG.md
lib/slimmer/processors/metadata_inserter.rb
lib/slimmer/processors/search_parameter_inserter.rb
lib/slimmer/version.rb

Nokogiri warning:
> warning: Passing a Node as the second parameter to Node.new is deprecated. Please pass a Document instead, or prefer an alternative constructor like Node#add_child. This will become an error in a future release of Nokogiri.
See 1.13.0 Nokogiri [deprecation notice](https://nokogiri.org/CHANGELOG.html#deprecated):
> Passing a Nokogiri::XML::Node as the second parameter to Node.new is deprecated and will generate a warning. This parameter should be a kind of Nokogiri::XML::Document. This will become an error in a future version of Nokogiri. [#975]

Resolve Nokogiri deprecation warning

---

CHANGELOG.md
lib/slimmer/version.rb

The changes for this felt like rather soft breaking changes so I've marked it as a major version.
I've also added a note for Plek.current since that might be of interest to updaters.

Release version 18.0.0

---

CHANGELOG.md
lib/slimmer.rb
lib/slimmer/processors/nonce_inserter.rb
lib/slimmer/skin.rb
test/processors/nonce_inserter_test.rb
test/typical_usage_test.rb

Trello: https://trello.com/c/lxxx5XLZ/178-govuk-has-a-half-implemented-content-security-policy-csp
We aspire [1] to use the GOV.UK Content Security Policy to only allow inline script elements on GOV.UK with the use of a nonce attribute [2]. This is to prevent cross-site-scripting in compliant browsers.
A challenge we have is that a rendering application (e.g. Frontend) may have inline scripts and a template provided by static may also have inline scripts and we need these to agree on the same nonce.
This change updates slimmer so that it will apply an applications nonce within HTML returned by static. Static will not set any nonce attributes.
For security, we need to run the NonceInserter processor before we Slimmer inserts any HTML from an app. As otherwise, in a scenario where someone …

Decorate inline script elements with CSP nonce

---

CHANGELOG.md
lib/slimmer/version.rb

This includes the ability to decorate inline script tag with nonce attributes for applications that use a Content Security Policy nonce.

Release 18.1.0

---

CHANGELOG.md
lib/slimmer/app.rb

References to Rack::Utils::HeaderHash now causing deprecation methods in email-alert-frontend. Replace with Rack::Headers, and remove unneeded to_h call.
Upgrade guide for Rack: https://github.com/rack/rack/blob/64610db2d2e7e910c4d3e17874dc316ed3eb227a/UPGRADE-GUIDE.md?plain=1#L237-L285
Example deprecation warning from test suite:
`/root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/slimmer-18.1.0/lib/slimmer/app.rb:45: warning: Rack::Utils::HeaderHash is deprecated and will be removed in Rack 3.1, switch to Rack::Headers`

Update reference to deprecated Rack::Utils::HeaderHash

---

slimmer.gemspec

Some of the apps relying on the gem don't require the newer versions of rack so are unaware of the breaking 3.0 change to Header.
More info: https://trello.com/c/Pr0ZtkxU/2248-bump-slimmer-dependabot

Enforce rack dependency to 3.0 or higher

---

CHANGELOG.md
lib/slimmer/version.rb

#316 - Upgrade minimum Ruby version to 3.2. Ruby 3.0 and 3.1 support has been removed.

Release 18.4.0

---

CHANGELOG.md
lib/slimmer.rb
lib/slimmer/processors/body_inserter.rb
lib/slimmer/skin.rb
test/processors/body_inserter_test.rb
test/typical_usage_test.rb

When wrapper is not found it results in a method being called on `nil`, which produces `NoMethodError`. For the purposes of investigating the error in the attached Trello card it would be useful to produce a more meaningful error containing some additional information which could help the investigation.
(Have added a feature flag, so this is only active when SLIMMER_WRAPPER_CHECK=true is set in the host app)
To facilitate the investigation of the error in the [Trello card](https://trello.com/c/iyPxdU09/2495-sentry-errors-investigate-frontend-nomethoderror)

Raise more specific error when wrapper not found

---

CHANGELOG.md
lib/slimmer/version.rb

* Raise more specific error when wrapper not found. This will only be active when the host app has SLIMMER_WRAPPER_CHECK=true set in the host app's environment.

Release 18.5.0

---

CHANGELOG.md
lib/slimmer/skin.rb

A further change related to https://github.com/alphagov/slimmer/pull/321
The initial investigation discovered that there is indeed some content in the body, but it does not contain a wrapper and it does not contain "\<html\>". This change will allow us to discover the initial part of the contents, so we can better understand what is being returned.

Include the initial part of the body in the error message

---

CHANGELOG.md
lib/slimmer/processors/body_inserter.rb
lib/slimmer/skin.rb
test/processors/body_inserter_test.rb
test/typical_usage_test.rb

We keep getting the following exception in production: https://govuk.sentry.io/issues/4958108827/?environment=production&environment=production-eks&environment=producton&project=-1&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=9
After [the discussion](https://gds.slack.com/archives/C052X8S2P8A/p1718796354165479) there was a suggestion to keep the SourceWrapperNotFoundError instead of reverting the PRs introducing it. I have removed the parts which were only meant to be used in the investigation of the issue and added a more explanatory message, so the issue is understood immediately after seeing the error. It cleans up after: https://github.com/alphagov/slimmer/pull/321, https://github.com/alphagov/slimmer/pull/330 and …

Update SourceWrapperNotFoundError handling

---

CHANGELOG.md
lib/slimmer/version.rb

* Remove the part of the body from the error message for SourceWrapperNotFoundError and do some cleanup Use more explanatory error message. Apply this globally to all apps.

Release 18.6.0

---

CHANGELOG.md
lib/slimmer/test_templates/header_footer_only.html
lib/slimmer/test_templates/wrapper.html

Update the `<script>` snippet in the test templates.
For govuk-frontend v5, there now needs to be additional class added to the `body` tag to indicate that the components are supported.
This class is `govuk-frontend-supported` and is added if the browser supports JS of type `module` (which is the new browser target for govuk-frontend).
The script tag is directly taken from the documentation, see "Update the `<script>` snippet at the top of your `<body>` tag" in the [release notes for govuk-frontend 5.0.0](https://github.com/alphagov/govuk-frontend/releases/tag/v5.0.0)
We can safely move to the new snippet in advance of upgrading to V5 of govuk-frontend and ensure components from govuk-frontend still initialise as expect when running integration tests from apps such as smart-answers. …

Update body classes for govuk frontend v5

---

CHANGELOG.md
lib/slimmer/version.rb

* Update body classes for govuk-frontend-v5 - ([PR #337](https://github.com/alphagov/slimmer/pull/337))

Release 18.6.1

---

CHANGELOG.md
lib/slimmer/processors/metadata_inserter.rb
test/processors/metadata_inserter_test.rb

Rename two of our metatags to remove `analytics` from them.
Must be deployed with: https://github.com/alphagov/govuk_publishing_components/pull/4222
Making them consistent with other metatags - we don't include `analytics` for other tags, even though they're used by analytics.
None.
Trello card: https://trello.com/c/lIVmnFpY/336-page-view-enhancement-some-meta-tags-start-with-analytics

Remove 'analytics' from metatags

---

CHANGELOG.md
lib/slimmer/version.rb

* Remove 'analytics' from metatags

Version 18.6.2

---

CHANGELOG.md
lib/slimmer/version.rb

* Use Ruby 3.3 as default https://github.com/alphagov/slimmer/pull/348

Release 18.7.0
