CHANGELOG.md, lib/slimmer/version.rb
=> Bump version to 8.0.0

CHANGELOG.md, lib/slimmer/version.rb
Bump version for new header. This is a non-breaking change.
=> Bump version to 8.1.0

README.md
I rewrote some of the test behaviour for components and couldn't remember how
it worked.
=> Improve the documentation for testing components

CHANGELOG.md, lib/slimmer/version.rb
Adds meta tag with current application name
=> Bump version to 8.2.0

lib/slimmer/app.rb
Depends on https://github.com/alphagov/static/pull/609
=> Add support for 403 error page.

CHANGELOG.md, lib/slimmer/version.rb
Adds support for 403 error page.
=> Bump to version 8.3.0.

README.md, lib/slimmer/cucumber.rb
Adds a test helper that configures Slimmer correctly under test.
=> Add Cucumber test helper

.gitignore, .yardopts, CONTRIBUTING.md, README.md, lib/slimmer/govuk_components.rb, lib/slimmer/headers.rb, slimmer.gemspec
This improves the documentation for this gem by removing outdated and irrelevant things and adding docs for the public API.
=> Add documentation

Jenkinsfile, Rakefile, slimmer.gemspec
This is a Jenkinsfile mostly copied from gds-api-adapters. We'll probably move this up to puppet soon.
=> Use Jenkinsfile to release new gems

lib/slimmer/i18n_backend.rb, test/i18n_backend_test.rb
This was introduced in https://github.com/alphagov/slimmer/pull/183 while copy-pasting the caching statements. Adds a test to prevent re-occurance.
https://trello.com/c/D9HmkJwI
=> Fix bug in I18n backend

CHANGELOG.md, lib/slimmer/version.rb
=> Release 10.1.1

CHANGELOG.md, lib/slimmer/skin.rb, lib/slimmer/version.rb
notify_sync was not available in airbrake v4
=> Fix call to airbrake

CHANGELOG.md, lib/slimmer/version.rb
* Add missing class tags to test templates for including Slimmer in tests
=> Release version 11.0.2

README.md
The component guide URL referred to in this repo has changed.
=> Update references to component guide

CHANGELOG.md, lib/slimmer/version.rb
* Make the 'Inside Header Inserter' more resillient so that it doesn't throw exceptions in a test context (#212)
=> Bump version to v11.1.1

CHANGELOG.md, lib/slimmer/version.rb
Releases https://github.com/alphagov/slimmer/pull/215.
https://trello.com/c/eKtXGtBD
=> Release version 12.0.0

CHANGELOG.md, lib/slimmer/version.rb
This removes the component code and lowers the cache TTL.
https://trello.com/c/pU7YINt1
=> Release version 13.0.0

CHANGELOG.md, lib/slimmer/version.rb
Trello card: https://trello.com/c/Ik7ulDXQ/1768-3-upgrade-frontend-to-rails-6
Co-Authored-By: Rebecca Pearce <beccapearce@users.noreply.github.com>
=> Bump version to 13.2.1

CHANGELOG.md, lib/slimmer/version.rb
https://trello.com/c/Uzpw1bDA/243-document-how-error-pages-work-on-govuk
=> Bump version to 14.0.0

CHANGELOG.md, lib/slimmer/version.rb
This PR updates Slimmer to version `15.1.0`.
=> Update to version 15.1.0

CHANGELOG.md, lib/slimmer/version.rb
Includes changes necessary to make [this ticket](https://trello.com/c/WLq4rKrW) happen: #251
=> Bump version to 15.1.1

CHANGELOG.md, lib/slimmer/version.rb
Includes 
* Add support for layout header component in static (#263)
=> Bump slimmer to 15.4.1

CHANGELOG.md, lib/slimmer/version.rb
Includes:
* Add support for gem layout in static (#265)
=> Bump Slimmer to v15.5.0

CHANGELOG.md, lib/slimmer/version.rb
Includes:
-  Update `gem_layout` template support (#267)
=> Bump Slimmer to v15.5.1

CHANGELOG.md, lib/slimmer/version.rb
Includes:
* Add feedback url swapper (#271)
=> Update to version 15.6.0

CHANGELOG.md, lib/slimmer/version.rb
Includes:
* Use safe navigation operator in feedback url swapper (#273)
=> Release v15.6.1

CHANGELOG.md, lib/slimmer/version.rb
=> Release v16.0.0

CHANGELOG.md, lib/slimmer/version.rb
Includes:
* BREAKING: https://github.com/alphagov/slimmer/pull/281
=> Release 17.0.0

CHANGELOG.md, lib/slimmer/version.rb
- https://github.com/alphagov/slimmer/pull/308
- https://github.com/alphagov/slimmer/pull/304
=> Release 18.2.0

CHANGELOG.md, lib/slimmer/version.rb
- https://github.com/alphagov/slimmer/pull/311
=> Release 18.3.0

CHANGELOG.md, lib/slimmer/version.rb
* Include a part of the body in the error message text
=> Release 18.5.1

CHANGELOG.md, lib/slimmer/skin.rb
FIx a silly mistake in PR #330
=> Fix mistake in PR #330

CHANGELOG.md, lib/slimmer/version.rb
=> Release 18.5.2
